version: '3'
services:
    flask:
        env_file:
            - .env
        build: ./flask
        container_name: flask
        restart: always
        ports:
            - 80:80
        volumes:
            - web-data:/home/ubuntu/app/
        links:
            - redis
            - celery
    celery:
        build: ./flask
        command : celery worker -l info -A flask.celery
        volumes:
            - '.:/flask'
        links:
            - redis
        depends_on:
            - redis
        container_name: cl01
    redis:
        image: 'redis:latest'
        # command:
        # volumes:
        #     - web-data:/home/ubuntu/app/
        container_name: rd01
        # ports:
        #     - 6379:6379
    # postgres:
    #     restart: always
    #     image: postgres:latest
    #     container_name: postgres
    #     volumes:
    #     - db-data:/home/ubuntu/app/
    #     ports:
    #     - "5432:5432"

volumes:
    web-data:
    # db-data: